php:
  image: dydx/alpine-nginx-phpfpm
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/sites-enabled
  links:
    - db:mysql
  ports:
    - "8080:80"
 
db:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./database2:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp